const redPlanet = "Mars";
console.log(redPlanet);
const greenForest = "Amazon";
console.log(greenForest);
const blueOcean = "Pacific";
console.log(blueOcean);
const nationalBird = "Peacock";
console.log(nationalBird);
const tallestAnimal = "Giraffe";
console.log(tallestAnimal);
const fastestAnimal = "Cheetah";
console.log(fastestAnimal);
const largestCountry = "Russia";
console.log(largestCountry);
const smallestCountry = "Vatican";
console.log(smallestCountry);
const famousMonument = "Taj Mahal";
console.log(famousMonument);
const programmingLanguage = "Python";
console.log(programmingLanguage);
const operatingDevice = "Android";
console.log(operatingDevice);
const searchEngine = "Google";
console.log(searchEngine);
const socialPlatform = "Instagram";
console.log(socialPlatform);
const videoPlatform = "YouTube";
console.log(videoPlatform);
const onlineStore = "Amazon";
console.log(onlineStore);
const paymentMethod = "UPI";
console.log(paymentMethod);
const musicalInstrument = "Guitar";
console.log(musicalInstrument);
const sportsVehicle = "Ferrari";
console.log(sportsVehicle);
const luxuryWatch = "Rolex";
console.log(luxuryWatch);
const smartAssistant = "Alexa";
console.log(smartAssistant);
const digitalWallet = "Paytm";
console.log(digitalWallet);
const spaceAgency = "NASA";
console.log(spaceAgency);
const weatherSeason = "Monsoon";
console.log(weatherSeason);
const movieIndustry = "Hollywood";
console.log(movieIndustry);
const learningPlatform = "Coursera";
console.log(learningPlatform);
const gamingConsole = "PlayStation";
console.log(gamingConsole); 
const cameraLens = "Canon";
console.log(cameraLens);
const fitnessTracker = "Fitbit";
console.log(fitnessTracker);
const internetBrowser = "Firefox";
console.log(internetBrowser);
const electricCompany = "Tesla";
console.log(electricCompany);
const streamingService = "Netflix";
console.log(streamingService);
const cloudPlatform = "AWS";
console.log(cloudPlatform);