let coffeeCup;
console.log(coffeeCup);
let teaGarden;
console.log(teaGarden);
let iceCream;
console.log(iceCream);
let chocolateBox;
console.log(chocolateBox);
let pizzaCorner;
console.log(pizzaCorner);
let burgerShop;
console.log(burgerShop);
let sandwichMaker;
console.log(sandwichMaker);
let fruitBasket;
console.log(fruitBasket);
let vegetableMarket;
console.log(vegetableMarket);
let bakeryOven;
console.log(bakeryOven);
let travelGuide;
console.log(travelGuide);
let passportNumber;
console.log(passportNumber);
let holidayResort;
console.log(holidayResort);
let beachHouse;
console.log(beachHouse);
let mountainRoad;
console.log(mountainRoad);
let bicycleHelmet;
console.log(bicycleHelmet);
let electricScooter;
console.log(electricScooter);
let carEngine;
console.log(carEngine);
let busTerminal;
console.log(busTerminal);
let railwayTrack;
console.log(railwayTrack);
let notebookCover;
console.log(notebookCover);
let classroomBoard;
console.log(classroomBoard);
let scienceLab;
console.log(scienceLab);
let computerMouse;
console.log(computerMouse); 
let gamingKeyboard;
console.log(gamingKeyboard);
let mobileCharger;
console.log(mobileCharger);
let headphoneJack;
console.log(headphoneJack);
let speakerStand;
console.log(speakerStand);
let televisionRemote;
console.log(televisionRemote);
let washingMachine;
console.log(washingMachine);    