var oceanWave;
console.log(oceanWave);
var forestPath;
console.log(forestPath);
var spaceRocket;
console.log(spaceRocket);
var mountainPeak;
console.log(mountainPeak);
var riverBridge;
console.log(riverBridge);
var sunsetView;
console.log(sunsetView);
var desertStorm;
console.log(desertStorm);
var jungleSafari;
console.log(jungleSafari);
var crystalBall;
console.log(crystalBall);
var silverArrow;
console.log(silverArrow);
var goldenTemple;
console.log(goldenTemple);
var rainbowColor;
console.log(rainbowColor);
var thunderCloud;
console.log(thunderCloud);
var winterSeason;
console.log(winterSeason);
var summerHoliday;
console.log(summerHoliday);
var villageMarket;
console.log(villageMarket);
var metroStation;
console.log(metroStation);
var airportLounge;
console.log(airportLounge);
var scienceProject;
console.log(scienceProject);
var codingChallenge;
console.log(codingChallenge);
